services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./Docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src:/var/www/html
    depends_on:
      - php

  php:
    build: ./Docker/php
    volumes:
      - ./src/:/var/www/html
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:9.0.1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: web_messenger
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - ./Docker/mysql/data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./Docker/redis/data:/data

