services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./Docker/nginx/web-messenger.conf:/etc/nginx/web-messenger.conf:ro
            - ./Docker/nginx/certs:/etc/nginx/certs
            - ./Docker/nginx/certs/generate-certs.sh:/docker-entrypoint.d/01-generate-certs.sh
            - ./src:/mnt/app
        depends_on:
            - php
        command: /bin/bash -c "ls -l /docker-entrypoint.d/ && chmod +x /docker-entrypoint.d/01-generate-certs.sh && /docker-entrypoint.d/01-generate-certs.sh && nginx -g 'daemon off;'"


    php:
        build: ./Docker/php
        ports:
            - "5173:5173"
            - "8080:8080"
        volumes:
            - ./src/:/mnt/app
            - ./Docker/nginx/certs:/mnt/certs
            - ./Docker/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mysql
            - redis

    mysql:
        image: mysql:9.0.1
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: web_messenger
            MYSQL_USER: user
            MYSQL_PASSWORD: user_password
            TZ: "UTC"
        volumes:
            - ./Docker/mysql/data:/var/lib/mysql

    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        volumes:
            - ./Docker/redis/data:/data

